@echo off
setlocal enabledelayedexpansion
REM Register the kimi-board service to start silently at logon (hidden window, no browser).
set "STARTUP=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
set "VBS=%STARTUP%\kimi-board.vbs"

REM Prefer the standalone exe; fall back to pythonw + script.
if exist "%~dp0kimi-board.exe" (
  set "RUNARGS=""%~dp0kimi-board.exe"" --no-open"
) else (
  set "PYW="
  for %%P in (pythonw.exe) do set "PYW=%%~$PATH:P"
  if not defined PYW (
    echo Neither kimi-board.exe nor pythonw.exe was found.
    echo Install Python 3.8+ and add it to PATH, or use the release zip with the exe.
    pause
    exit /b 1
  )
  set "RUNARGS=""!PYW!"" ""%~dp0kimi_board.py"" --no-open"
)

> "%VBS%" echo ' kimi-board autostart (generated by install-autostart.bat)
>> "%VBS%" echo CreateObject("Wscript.Shell").Run "%RUNARGS%", 0, False

REM Start it right away too (unless already running).
curl -s -o nul --max-time 2 http://127.0.0.1:8321/
if %errorlevel%==0 (
  echo The service is already running: http://127.0.0.1:8321
) else (
  wscript "%VBS%"
  echo Started now, and will auto-start at every logon.
)

echo Registered: %VBS%
echo The board service will start silently at next logon: http://127.0.0.1:8321
echo To undo, run uninstall-autostart.bat or delete that vbs file.
pause
